// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxnojqgedftvdzdmyugh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4bm9qcWdlZGZ0dmR6ZG15dWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NzY2MzMsImV4cCI6MjA2MTQ1MjYzM30.yrgnFTNKuhv0_dzPHKaDubFwGIB2Ctu-QTsBQ5_iAnA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);